test-declarative: assert needs refusal to operate from subshells

diff --git a/test-declarative b/test-declarative
--- a/test-declarative
+++ b/test-declarative
@@ -92,6 +92,10 @@ leak_test() {
 
 main() {
     # we need all tests; run them in order.
+    (needs test 2>/dev/null) && {
+        echo "ERROR: Must refuse to satisfy dependencies within subshells" >&2
+        return 1
+    }
     needs test
     echo "SUCCESS"
 }
